### ISSUE TITLE
Unable to load data

### ISSUE THREAD

**Issue by alejoe91** [jwouters91/shybrid#5]
Hi @jwouters91 

I'm trying to load some data to SHYBRID, but I get an error. 
I saved the data to binary C format , dtype=float32 and the clusters are in phy template-gui format. 

This is my recording.yml:
```
clusters:
  phy: phy-folder
data:
  dtype: float32
  fs: 32000
  order: C
  probe: probe_file.prb
```

In the GUI I get this error which is very hard to debug:
![image](https://user-images.githubusercontent.com/17097257/68588407-b6ac5780-0489-11ea-8eff-8e1a8cd76f29.png)

The data are generated with MEArec, saved to bin file and prb and phy format with spikeinterface.

Any idea what could be the reason?
